# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 682)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        Form.setFont(font)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 130, 571, 339))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.le_sheetPath = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_sheetPath.setReadOnly(True)
        self.le_sheetPath.setObjectName("le_sheetPath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.le_sheetPath)
        self.btn_findSheet = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_findSheet.setObjectName("btn_findSheet")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.btn_findSheet)
        self.lb_chooseSheet = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_chooseSheet.setObjectName("lb_chooseSheet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lb_chooseSheet)
        self.cb_chooseSheet = QtWidgets.QComboBox(self.formLayoutWidget)
        self.cb_chooseSheet.setObjectName("cb_chooseSheet")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_chooseSheet)
        self.lb_idFirst = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_idFirst.setObjectName("lb_idFirst")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lb_idFirst)
        self.le_idFirst = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_idFirst.setObjectName("le_idFirst")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.le_idFirst)
        self.lb_nameFirst = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_nameFirst.setObjectName("lb_nameFirst")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lb_nameFirst)
        self.le_nameFirst = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_nameFirst.setObjectName("le_nameFirst")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.le_nameFirst)
        self.lb_pointsFirst = QtWidgets.QLabel(self.formLayoutWidget)
        self.lb_pointsFirst.setObjectName("lb_pointsFirst")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lb_pointsFirst)
        self.le_pointsFirst = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.le_pointsFirst.setObjectName("le_pointsFirst")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.le_pointsFirst)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.lb_title = QtWidgets.QLabel(Form)
        self.lb_title.setGeometry(QtCore.QRect(10, 10, 621, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.lb_title.setFont(font)
        self.lb_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lb_title.setObjectName("lb_title")
        self.btn_back = QtWidgets.QPushButton(Form)
        self.btn_back.setGeometry(QtCore.QRect(10, 70, 181, 42))
        self.btn_back.setObjectName("btn_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "定位设置"))
        self.btn_findSheet.setText(_translate("Form", "选择表格文件"))
        self.lb_chooseSheet.setText(_translate("Form", "待编辑工作表"))
        self.lb_idFirst.setText(_translate("Form", "学号列首单元格"))
        self.le_idFirst.setText(_translate("Form", "(,)"))
        self.lb_nameFirst.setText(_translate("Form", "姓名列首单元格"))
        self.le_nameFirst.setText(_translate("Form", "(,)"))
        self.lb_pointsFirst.setText(_translate("Form", "积分列首单元格"))
        self.le_pointsFirst.setText(_translate("Form", "(,)"))
        self.label.setText(_translate("Form", "单元格坐标格式样例：(A,1)，符合正则表达式：\n"
"^([A-Z]*,[0-9]*)$\n"
"已进行正则强校验，不符合要求的修改将忽略"))
        self.lb_title.setText(_translate("Form", "定位设置"))
        self.btn_back.setText(_translate("Form", "保存并返回"))
